name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nuclei
        run: |
          sudo apt-get update
          sudo apt-get install -y golang
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

      - name: Run DAST Scan
        run: |
          nuclei -update-templates
          nuclei -u https://youngowl13.github.io/zap-test/ -t ~/nuclei-templates/ -o report.html -t html

      - name: Save Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dast-report
          path: report.html
