name: Install Nuclei

on:
  push:
    branches:
      - main

jobs:
  install-nuclei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python3 and pip3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: Install Nuclei
        run: |
          sudo pip3 install nuclei

      - name: Verify Nuclei Installation
        run: |
          nuclei -version
