name: OWASP ZAP DAST Scan

on:
    # schedule:
    # - cron: "15 15 * * *"
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    dast:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Run ZAP scan
              uses: zaproxy/action-full-scan@v0.4.0
              with:
                  target: "https://youngowl13.github.io/zap-test/"
                  cmd_options: "-a"

            - name: Save ZAP report
              uses: actions/upload-artifact@v2
              with:
                  name: ZAP Report
                  path: zap-report.html
              env:
                  GITHUB_TOKEN: ${{ secrets.TEST1 }}
